# Generated by Django 4.0.6 on 2022-12-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='url',
        ),
    ]
