# Generated by Django 4.0.6 on 2022-12-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
